-- ============================================
-- DEMO SEED: fictional musicians for the public /demo pages
--
-- Everything here is made up: five fictional people (surnames are music
-- terms), about eight weeks of practice sessions ending today, kudos,
-- comments, follows and two synthesized audio clips served from
-- public/demo/clips/ (generated by scripts/generate-demo-clips.mjs;
-- they are tones, not recordings).
--
-- Requires migrations 001-014. Run it in the Supabase SQL editor (it
-- needs to write to auth.users). Re-running replaces the demo data.
-- Sessions are generated deterministically relative to now(); the /demo
-- pages also shift demo dates forward so the latest session is always
-- within the last day.
--
-- The demo accounts have no password and an .invalid email address, so
-- nobody can sign in as them, and migration 014 makes their data
-- read-only for every API user.
-- ============================================

BEGIN;

CREATE TEMP TABLE demo_people (
  id UUID PRIMARY KEY,
  username TEXT NOT NULL,
  display_name TEXT NOT NULL,
  instrument TEXT NOT NULL,
  bio TEXT NOT NULL,
  weekly_goal_minutes INTEGER,
  practice_rate INTEGER NOT NULL,   -- % chance of practicing on a given day
  streak_days INTEGER NOT NULL,     -- guaranteed practice for the most recent N days
  usual_hour INTEGER NOT NULL,      -- UTC hour they usually practice
  base_minutes INTEGER NOT NULL,
  spread_minutes INTEGER NOT NULL,
  pieces TEXT[] NOT NULL,
  skills TEXT[] NOT NULL
) ON COMMIT DROP;

INSERT INTO demo_people VALUES
  ('d0000000-0000-4000-8000-000000000001', 'ada_quaver', 'Ada Quaver', 'Piano',
   'Fictional demo musician. Returning pianist, practicing before work.',
   300, 70, 12, 6, 25, 35,
   ARRAY['Chopin: Nocturne Op. 9 No. 2', 'Bach: Prelude in C major, BWV 846', 'Scales and arpeggios'],
   ARRAY['Voicing the melody', 'Pedaling', 'Hands separately, slow', 'Evenness at 80 bpm']),
  ('d0000000-0000-4000-8000-000000000002', 'theo_arpeggio', 'Theo Arpeggio', 'Guitar',
   'Fictional demo musician. Classical guitar, mostly in the evenings.',
   240, 60, 5, 19, 20, 40,
   ARRAY['Tárrega: Lágrima', 'Villa-Lobos: Étude No. 1', 'Travis picking drills'],
   ARRAY['Right-hand arpeggios', 'Rest strokes', 'Barre chords', 'Slurs']),
  ('d0000000-0000-4000-8000-000000000003', 'mira_fermata', 'Mira Fermata', 'Cello',
   'Fictional demo musician. Community orchestra cellist.',
   420, 80, 21, 17, 35, 45,
   ARRAY['Bach: Cello Suite No. 1, Prelude', 'Saint-Saëns: The Swan', 'Long tones'],
   ARRAY['Bow distribution', 'Shifting', 'Intonation with drone', 'Vibrato']),
  ('d0000000-0000-4000-8000-000000000004', 'jun_staccato', 'Jun Staccato', 'Drums',
   'Fictional demo musician. Weekend drummer in a covers band.',
   NULL, 45, 2, 20, 30, 30,
   ARRAY['Paradiddle ladder', 'Half-time shuffle groove', 'Rudiment warm-up'],
   ARRAY['Ghost notes', 'Metronome on 2 and 4', 'Left-hand lead', 'Fills']),
  ('d0000000-0000-4000-8000-000000000005', 'rosa_cadenza', 'Rosa Cadenza', 'Violin',
   'Fictional demo musician. Adult beginner, second year of violin.',
   180, 55, 3, 7, 15, 25,
   ARRAY['Kreutzer: Étude No. 2', 'Bach: Partita No. 2, Allemande', 'Vibrato exercises'],
   ARRAY['Bow hold', 'Third position', 'String crossings', 'Tuning by ear']);

-- Deterministic "randomness": a stable number in [0, m) from any text.
CREATE OR REPLACE FUNCTION pg_temp.pick(seed TEXT, m INTEGER) RETURNS INTEGER
LANGUAGE sql IMMUTABLE AS $$
  SELECT (((hashtext(seed)::BIGINT % m) + m) % m)::INTEGER
$$;

-- 1. Replace any previous demo data (cascades to profiles and all their rows)
DELETE FROM auth.users WHERE id IN (SELECT id FROM demo_people);

-- 2. Accounts. handle_new_user creates each profile from raw_user_meta_data.
--    No password and an .invalid address: these accounts cannot sign in.
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
)
SELECT
  '00000000-0000-0000-0000-000000000000', id, 'authenticated', 'authenticated',
  username || '@demo.virtuoso.invalid', '', now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('username', username, 'full_name', display_name),
  now() - interval '70 days', now() - interval '70 days',
  '', '', '', ''
FROM demo_people;

UPDATE public.profiles p
SET is_demo = true,
    display_name = d.display_name,
    bio = d.bio,
    primary_instrument = d.instrument,
    account_type = 'public',
    weekly_goal_minutes = d.weekly_goal_minutes,
    created_at = now() - interval '70 days'
FROM demo_people d
WHERE p.id = d.id;

-- 3. Everyone follows everyone except Jun -> Rosa and Rosa -> Jun
INSERT INTO public.follows (follower_id, following_id, created_at)
SELECT a.id, b.id, now() - interval '60 days'
FROM demo_people a
JOIN demo_people b ON a.id <> b.id
WHERE NOT (a.username = 'jun_staccato' AND b.username = 'rosa_cadenza')
  AND NOT (a.username = 'rosa_cadenza' AND b.username = 'jun_staccato');

-- 4. Sessions: ~8 weeks, one per practice day, some manual entries
WITH days AS (
  SELECT d.*, day_offset,
         (d.username || ':' || day_offset) AS seed
  FROM demo_people d
  CROSS JOIN generate_series(0, 55) AS day_offset
),
practice_days AS (
  SELECT *,
         base_minutes + pg_temp.pick(seed || ':len', spread_minutes + 1) AS minutes,
         date_trunc('day', now()) - make_interval(days => day_offset)
           + make_interval(hours => usual_hour, mins => pg_temp.pick(seed || ':min', 50)) AS started_at,
         pg_temp.pick(seed || ':manual', 7) = 0 AS is_manual
  FROM days
  WHERE day_offset < streak_days
     OR pg_temp.pick(seed || ':practice', 100) < practice_rate
)
INSERT INTO public.sessions (
  user_id, instrument, duration_seconds, break_seconds, break_timeline,
  piece_name, skills_practiced, description, focus, entropy, enjoyment,
  is_manual_entry, created_at, updated_at
)
SELECT
  id,
  instrument,
  minutes * 60,
  CASE WHEN NOT is_manual AND minutes >= 40 THEN 300 ELSE 0 END,
  CASE WHEN NOT is_manual AND minutes >= 40
       THEN jsonb_build_array(jsonb_build_object('start', (minutes * 60) / 2, 'end', (minutes * 60) / 2 + 300))
       ELSE '[]'::jsonb END,
  pieces[1 + pg_temp.pick(seed || ':piece', array_length(pieces, 1))],
  skills[1 + pg_temp.pick(seed || ':skill', array_length(skills, 1))],
  NULL,
  (ARRAY['clear_goals', 'clear_goals', 'mid', 'noodling'])[1 + pg_temp.pick(seed || ':focus', 4)],
  (ARRAY['few_measures', 'in_between', 'in_between', 'whole_piece'])[1 + pg_temp.pick(seed || ':entropy', 4)],
  (ARRAY['progress', 'progress', 'ok', 'stuck'])[1 + pg_temp.pick(seed || ':enjoy', 4)],
  is_manual,
  started_at,
  started_at
FROM practice_days
WHERE started_at <= now() - interval '15 minutes';

-- A few hand-written notes on recent sessions
WITH ranked AS (
  SELECT s.id, p.username,
         row_number() OVER (PARTITION BY s.user_id ORDER BY s.created_at DESC) AS n
  FROM public.sessions s JOIN demo_people p ON p.id = s.user_id
)
UPDATE public.sessions s
SET description = notes.note
FROM ranked r
JOIN (VALUES
  ('ada_quaver', 1, 'Left hand finally quiet enough in bars 5-8. Recorded a take to compare tomorrow.'),
  ('ada_quaver', 3, 'Slow practice with the metronome at 60. Boring but it works.'),
  ('theo_arpeggio', 1, 'Lágrima B section at tempo for the first time. Clip attached.'),
  ('mira_fermata', 1, 'Prelude from memory, with a drone for the tricky shifts.'),
  ('mira_fermata', 2, 'Orchestra rehearsal tomorrow, ran the Swan twice with a recording.'),
  ('jun_staccato', 1, 'Shuffle feels better with the hi-hat ghost notes lighter.'),
  ('rosa_cadenza', 1, 'Third position shifts are landing more often. Still flat on the E string.')
) AS notes(username, n, note) ON notes.username = r.username AND notes.n = r.n
WHERE s.id = r.id;

-- 5. Kudos from other demo musicians on sessions from the last three weeks
INSERT INTO public.kudos (user_id, session_id, created_at)
SELECT giver.id, s.id, s.created_at + interval '3 hours'
FROM public.sessions s
JOIN demo_people owner ON owner.id = s.user_id
JOIN demo_people giver ON giver.id <> owner.id
WHERE s.created_at > now() - interval '21 days'
  AND pg_temp.pick(giver.username || ':' || owner.username || ':' || s.created_at::date::text, 100) < 45
  AND s.created_at + interval '3 hours' < now();

-- 6. Comments on each musician's latest sessions
WITH ranked AS (
  SELECT s.id, s.created_at, p.username,
         row_number() OVER (PARTITION BY s.user_id ORDER BY s.created_at DESC) AS n
  FROM public.sessions s JOIN demo_people p ON p.id = s.user_id
),
lines(owner, n, author, minutes_after, body) AS (VALUES
  ('ada_quaver', 1, 'mira_fermata', 40, 'Twelve days in a row! The nocturne is really coming together.'),
  ('ada_quaver', 1, 'theo_arpeggio', 95, 'Recording yourself is such a good idea. Stealing that.'),
  ('ada_quaver', 3, 'rosa_cadenza', 60, 'Metronome at 60 is my whole life right now.'),
  ('theo_arpeggio', 1, 'ada_quaver', 30, 'That B section clip is gorgeous.'),
  ('theo_arpeggio', 1, 'jun_staccato', 120, 'Clean! What tempo are you at now?'),
  ('theo_arpeggio', 1, 'theo_arpeggio', 150, 'About 66 to the quarter, want to get to 72.'),
  ('mira_fermata', 1, 'ada_quaver', 25, 'From memory! Impressive.'),
  ('mira_fermata', 2, 'rosa_cadenza', 70, 'Good luck at rehearsal tomorrow!'),
  ('jun_staccato', 1, 'theo_arpeggio', 45, 'Lighter ghost notes is the secret, agreed.'),
  ('rosa_cadenza', 1, 'mira_fermata', 35, 'Try a drone on A for the E-string shifts, it helped me a lot.'),
  ('rosa_cadenza', 1, 'rosa_cadenza', 80, 'Will do, thanks!')
)
INSERT INTO public.comments (user_id, session_id, content, created_at, updated_at)
SELECT author.id, r.id, l.body,
       r.created_at + make_interval(mins => l.minutes_after),
       r.created_at + make_interval(mins => l.minutes_after)
FROM lines l
JOIN ranked r ON r.username = l.owner AND r.n = l.n
JOIN demo_people author ON author.username = l.author
WHERE r.created_at + make_interval(mins => l.minutes_after) < now();

-- 7. Synthesized clips (static files in public/demo/clips/), no storage objects
INSERT INTO public.snippets (session_id, user_id, audio_url, start_time_ms, duration_ms, created_at)
SELECT r.id, r.user_id, clip.url,
       GREATEST(0, r.duration_seconds * 1000 - 5 * 60 * 1000), -- five minutes before the end
       clip.duration_ms, r.created_at
FROM (
  SELECT s.id, s.user_id, s.created_at, s.duration_seconds, p.username,
         row_number() OVER (PARTITION BY s.user_id ORDER BY s.created_at DESC) AS n
  FROM public.sessions s JOIN demo_people p ON p.id = s.user_id
  WHERE NOT s.is_manual_entry
) r
JOIN (VALUES
  ('theo_arpeggio', '/demo/clips/plucked-arpeggio.wav', 10000),
  ('ada_quaver', '/demo/clips/piano-phrase.wav', 10000)
) AS clip(username, url, duration_ms) ON clip.username = r.username
WHERE r.n = 1;

COMMIT;
